spring:

  datasource:
    url: spring.datasource.url=mysql://bcc301af198574:c4301e33@us-cdbr-iron-east-04.cleardb.net/heroku_c1a5f1a4c39acab?reconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
